name: CI

on:
  pull_request:
    branches:
      - develop
      - qa
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  database-reconstruction:
    uses: ./.github/workflows/db-ci.yml
